name: Build and Deploy React App to Simply.com

# Trigger the workflow on push to main branch
on:
  push:
    branches: [ main ]
  # Allow manual triggering from GitHub UI
  workflow_dispatch:

jobs:
  build_and_deploy:
    name: Build and Deploy to Simply.com
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build React app
        run: npm run build
        env:
          # Add any environment variables your build needs
          CI: false

      - name: Deploy to Simply.com
        uses: rasmusbuchholdt/simply-web-deploy@2.2.0
        with:
          website-name: ${{ secrets.WEBSITE_NAME }}
          server-computer-name: ${{ secrets.SERVER_COMPUTER_NAME }}
          server-username: ${{ secrets.SERVER_USERNAME }}
          server-password: ${{ secrets.SERVER_PASSWORD }}
          source-path: '\build\'
          target-delete: true  # This deletes old files, good for React apps